language: php

php:
    - 5.6
    - 7.0
    - hhvm

matrix:
    allow_failures:
        - php: hhvm

sudo: false

before_script:
    - composer install

script:
    - ./vendor/bin/phpunit --configuration ./app/phpunit.xml.dist

after_script:
    - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then wget https://scrutinizer-ci.com/ocular.phar; fi
    - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml; fi
